### ISSUE TITLE
Project Foldering

### ISSUE THREAD

**Issue by isatrio** [mentoring-front-end/Shopping-Cart#12]
Do proper foldering for the project.

*Project folder*
```
|- src // all project goes here
   |-- assets // all images/multimedia goes here
   |-- components // all components goes here
   |-- styles // all global styles goes here
   |-- helper // all little functions goes here
|- tests // all tests goes here
```

*Component folder template and files*
```
|- components
   |-- component-name
        |-- component.ts
        |-- component.scss // with note: this style is only for local style
   |-- component-name
        |-- component.ts
        |-- component.scss
```

**Comment by abdillahadam20** [comment]
Aku ada beberapa pertanyaan terkait struktur folder ini mas.

1. Untuk htmlwebplugin di src/template/index.htmlnya itu apakah harus di hapus dan di pindahin ke src/ aja atau tetap disitu ?
2. Untuk src/index.ts itu apakah di masukkin ke component atau itu tetap disitu ?
3. styles.scss itu sama _color dan sebagainya yang sama dengan itu apakah masuknya di styles (all global styles) ?
4. Terkait component itu kan per component seperti di react yah kayak navbar terus card gitu2 nah itu untuk scssnya nanti di import di style global atau gimana ya mas ? apakah untuk styling di global itu tetap mas ?

Terima kasih.

**Comment by isatrio** [comment]
1. Untuk index.html bisa buat 1 folder public yang isinya itu aja
2. Khusus index.ts biarkan aja di src tanpa masuk ke folder manapun
3. Yang sifatnya global, masukkan ke folder global. Yang sifatnya hanya lokal masukkan ke component yang bersangkutan
4. Mengacu ke jawaban nomor 3. Rulenya if it's global, import it on global, if it's local import it on local.
5. Test nanti untuk bikin test, bisa unit atau behave. Tapi nanti aja dulu.
