### ISSUE TITLE
Find a reset.css or normalize.css

### ISSUE THREAD

**Issue by isatrio** [mentoring-front-end/Shopping-Cart#16]
Remove this one below and find and use reset or normalize CSS instead

```
* {
	padding: 0;
	margin: 0;
	box-sizing: border-box;
}
```

**Comment by rishvantsingh** [comment]
I will do this. Allot it to me .

**Comment by abdillahadam20** [comment]
Done juga mas, untuk reset pake normalize.css. 

CMIIW mas.
