### ISSUE TITLE
Re-porting existing builder from react to vanilla TypeScript

### ISSUE THREAD

**Issue by isatrio** [mentoring-front-end/Shopping-Cart#2]
For a crystal clear writing code, I suggested using TypeScript.

## What to do?

chore: setup TS builder

1. Do find references for Webpack feat. TypeScript. There are a bunch of them. Use that fit with your need.
2. Because basically TypeScript is JavaScript and beyond. So, do a little read on the docs. It will be hard at first, please be patient.

notes: The setup will include a ts-loader and config on webpack.config and tsconfig.json. Again, be patient

In the end, we will try to create some framework components for some famous frameworks.

**Comment by abdillahadam20** [comment]
Setup builder untuk TS dan juga Tailwindcssnya sudah di PR mas. Kindly check.

Bug:
1. Untuk typescript penambahan kode baru tidak mau masuk ketidak sudah di npm run serve nya
2. Untuk tailwindcssnya tidak mau muncul di index.htmlnya walapun pake pake valet linuxnya

Mohon bantuannya untuk diarahkan setup confignya apakah ada yang salah.

Terima kasih.
