### ISSUE TITLE
Create several commands on packages.json

### ISSUE THREAD

**Issue by isatrio** [mentoring-front-end/Shopping-Cart#3]
Once we used an automated scaffolding like `create-react-app` they infected us with expectations. Now your turn to fulfill your expectation. This time I'll let you find the answer.

feat: add several commands on packages.json

1. Add environment on the commands, so we can choose which environment we will use. Usually, there are 3 environments used by developers: `local`, `staging`, `production`. The goal is to make them available
2. One command is for one thing, if you want to do more than one so you need to use multiple command runners. This is an issue why your `serve` is not reloading, because it's not `watching` the files change.
3. Later on we can use these commands for our GitHub Actions.

Cheers

**Comment by abdillahadam20** [comment]
Mas untuk setup environment di package.json bisa kasih tau lebih detail gak ? Aku udah cari-cari referensi di documentasi sama liat-liat repo punya orang untuk webpack.config.json sama package.jsonnya tapi gak paham setupnya gimana untu NODE_ENV. Untuk `local`, `staging` sama `production` nya. Terima kasih

**Comment by abdillahadam20** [comment]
Untuk environmentnya sudah ku tambahkan mas, tapi aku masih kurang paham bedanya sama production kan sama2 aja ya ujung2nya itu buat build project di akhir.  Untuk reloading command sudah ku tambahkan.

**Comment by isatrio** [comment]
Jadi perbedaannya antara production sama development. Hasil build-nya itu kalo production akan terkompres dan kalo development nggak. Coba cek build production sama development. Any way it's finish, next issue
