### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by isatrio** [mentoring-front-end/Shopping-Cart#7]
Since the setup is done, we move to create a card component.

feat: card component

Based on this layout https://www.figma.com/community/file/1030799232848044542 (ignore the dot colors). Please create a card component. The content inside is below:

1. Image thumbnail
2. Title
3. Price: it will be a nominal and currency
4. Instant add to cart: the button design please follow any button available in the design

Anything unclear please let me know

**Comment by abdillahadam20** [comment]
Already done and just creating pull request for checking the task, thank you mas. Have a nice day :)

**Comment by isatrio** [comment]
Move on to next ticket
